### ISSUE TITLE
How can you remove NoFollow Attribut from the Forum

### ISSUE THREAD

**Issue by AlexL777** [dreamhearth/fireside#22]
Hello Developers,

I am a German user of Fierside and have your forum Tool first discovered and seen today. I think it's good that there is a fork of EsoTalk and I would like to know how you can remove the NoFollow attribute on the forum.

In my case it is an internal test project and the external links will be known to me the link references. So I want that Google can follow the links.

How can I accomplish it?

Thanks in advance.

**Comment by Felli** [comment]
As much as I (And most likely even @jsonnull ) like, Fireside is still undergoing it's transformation so using it isn't 100% a good idea to use it till it's completed for at least a beta or at least alpha.

**Comment by jsonnull** [comment]
Right now we're right in the middle of a conversion from the current, raw PHP view layer to Handlebars templates. Currently it's hard to do this kind of low-level change, but with Handlebars it'll be much easier to make these changes, and you'll be able to do so in a way that does not modify the core files. If you're interested in trying out an early version, stay tuned for a 2.0 alpha in the next few weeks.

**Comment by AlexL777** [comment]
OK, thank you very much for your answers. I have already installed the forum and create some content. I think I'll like to follow the development of Fireside. It interests me a bit.
