### ISSUE TITLE
How to create static pages such as imprint or Privacy Policy

### ISSUE THREAD

**Issue by AlexL777** [dreamhearth/fireside#23]
Hello Developers,

available at Fireside have a way how to create static pages or you can use the plugin Pages of Esotalk?

Thank you in advance.

**Comment by Felli** [comment]
There is a plugin on the esoTalk forums called [Static Page](http://esotalk.org/forum/845-static-pages) this is the easiest way other than manually creating one.

**Comment by jsonnull** [comment]
@Felli is correct here.

It's important to note that the 2.x branch will not support esoTalk plugins without modification. If you're looking for all the new features coming into 2.0 you may want to hold off on deciding a static pages solution until that is released.

**Comment by AlexL777** [comment]
Yes, this plugin I use also.

That's what I've been thinking that Fireside will be its own software without esoTalk. Ok, I'm still waiting for some time before the Forum system has developed.

But quite interesting when you can create static pages. You you need in the forum definitely :)

**Comment by jsonnull** [comment]
> Fireside will be its own software without esoTalk

Once we hit 2.x Fireside will not support esoTalk skins; plugins will require modification to stay compatible.

**Comment by AlexL777** [comment]
Then I must a fortiori be patient, because I have already installed some plugins esoTalk me.

Well, well, then it will be so.

**Comment by jsonnull** [comment]
I'll be porting several esoTalk plugins myself, if you'd care to let me know which plugins you're currently using I'll take that under consideration when selecting which plugins I'll be supporting conversion of.

**Comment by AlexL777** [comment]
Many thanks!

I currently use such EsoTalk plugins like Signature, Views, Attachments, Emoticons Plus, Share.

Still it would be interesting if you could set the external links in the forum via option on DoFollow. That is determined interest some forum users.

Otherwise, this is the first time anything. I have been following your development times then.

**Comment by jsonnull** [comment]
Views, Attachments, Signature will definitely be ported. I don't yet know about Emoticons Plus or Share, we'll see.

**Comment by AlexL777** [comment]
Well, let's make it so!

**Comment by Felli** [comment]
@jsonnull Personally I think the Share, Attactments, & Signature could easily be added to the core (In extreme circumstances of course.)

**Comment by jsonnull** [comment]
@Felli I'm inclined to agree. However, I think part of the reason this has never been done is that esoTalk marketed itself as an extremely lightweight solution. On shared hosting lighter is a LOT better, so the philosophy was that if it wasn't necessary for the core experience let users add it but don't force it on users that want the lightest solution possible.

**Comment by Felli** [comment]
@jsonnull Very true, tho this is just for extreme circumstances. lol
